<?php
/**
 * @file
 * Provides a Views style plugin to display content in a byu card.
 */

/**
 * Implements hook_views_api().
 */
function views_card_d7_views_api() {
  return array('api' => '3.0');
}

/**
 * Set default options.
 */
function views_card_d7_get_options($array) {
  $options = array();
  foreach ($array as $key => $value) {
    if (!is_array($value)) {
      $options[$key] = $value;
    }
    else {
      $options = array_merge($options, views_card_d7_get_options($value));
    }
  }
  return $options;
}

/**
 * Display a view as a byu card style.
 */
function template_preprocess_views_view_byu_card(&$vars) {
  drupal_add_js('https://cdn.byu.edu/byu-card/unstable/my-component.js', 'external');
  $view = $vars['view'];
//  $result = $view->result;
  $options = views_card_d7_get_options($view->style_plugin->options);
//  $handler = $view->style_plugin;
  $columns  = $options['columns'];

  if (!empty($vars['rows'])) {

    $vars['card_width'] = array();
    foreach ($vars['rows'] as $i => $row) {
      $widthClass = 'columns-' . $columns;
      $vars['card_width'][$i] = $widthClass;
      $vars['cols'][$i] = $columns;
    }
  }
}
